### PR TITLE
[8.0.x] serf deprecation mode

### PR DESCRIPTION
**Pull request by a-palchikov**
Complementary PR for https://github.com/gravitational/gravity/pull/2638. See the gravity PR for motivation.

This PR needs to be merged against a version/8.0.x branch since it is not intended for changes in 9.x - can a code-owner create a branch if this PR is accepted?

### CODE REVIEW

**Review by bernardjkim — APPROVED** [review]

**Review by wadells — APPROVED** [review]

**Comment by a-palchikov** [comment]
can any of the admins merge this PR?

**Comment by a-palchikov** [comment]
Please do not merge just yet - I stumbled on a corner case I'd like to cover.

**Comment by a-palchikov** [comment]
@gravitational/codeowners-gravity-code Can any of the admins merge this? It's good to go.

**Comment by wadells** [comment]
> @gravitational/codeowners-gravity-code Can any of the admins merge this? It's good to go.

Done.  I left it as merge commit -- since the commit history had some valuable info in it, and I didn't feel comfortable editorializing by rebasing, e.g. to remove the `wip` commit.  If we need to merge more on you're behalf, we can discuss either getting you a commit bit to this repo or figure out expectations around merge (e.g. stuff will get squashed, or make sure to have a final draft of the history before requesting merge).

**Comment by wadells** [comment]
I've tagged https://github.com/gravitational/satellite/tree/8.0.2, amusingly a descendant of 9.0.0. :smile:

**Pull request merged**
