### PR TITLE
Serf deprecation mode

### PR DESCRIPTION
**Pull request by a-palchikov**
Forward port of https://github.com/gravitational/satellite/pull/302 with changes in the context of 9.x (e.g. no need to support old-style agent name).
This is the final step towards complete elimination of serf and these changes are required to support upgrading older 9.x clusters.

### CODE REVIEW

**Comment by wadells** [comment]
I'm a bit confused -- why does this need to be forward ported to 9.0.x?  Based on the notes in https://github.com/gravitational/gravity/pull/2638, I thought the new compatibily mode was only relevant during the 7.0 -> 8.0 upgrades, and we wouldn't need to support changes from 8.0 -> 9.0 going forward.

I.E. 9.0 nodes should never be talking to 7.0 nodes, that is outside our supported upgrade policy.

**Comment by a-palchikov** [comment]
These changes are required to support upgrading from an older version of 9.x since the agent APIs have been altered with the introduction of the new `NodeName` attribute. This, the 9.x version is still a bridge - everything can be removed only in a 10.x.

**Review by bernardjkim — APPROVED** [review]

**Review by wadells — APPROVED** [review]

**Comment by a-palchikov** [comment]
@wadells Can you please merge this at your next convenience?

**Comment by wadells** [comment]
> @wadells Can you please merge this at your next convenience?

Merged, and 9.0.1 tagged.

**Pull request merged**
