### PR TITLE
Updated go-systemd to latest version

### PR DESCRIPTION
**Pull request by eldios**
Updated coreos/go-systemd to the latest version (v16).

### CODE REVIEW

**Comment by UnderGreen** [comment]
@eldios, as I remember I set library version to 4.0 especially. Make sense to check monitoring of systemd units, maybe it is broken now.

**Comment by a-palchikov** [comment]
There were no changes to `go-systemd` since migration to `dep` as far as I could tell.

**Comment by eldios** [comment]
@UnderGreen thanks for mentioning that.. we were trying to understand why we were stuck with that specific version.
I tried compiling `satellite` using a simple `make` and it worked... `make test` is segfaulting for me, but I guess that's bound to the fact that I'm using Go 1.10 ?

**Comment by eldios** [comment]
@a-palchikov in version 4.0.0 a few functions were not implemented yet... that's why the idea to move on to a newer version.

**Comment by a-palchikov** [comment]
I meant that we did not change the version of `go-systemd` since the repository was migrated to `dep`.

**Comment by eldios** [comment]
testing

**Comment by eldios** [comment]
Finally manually verified, it's working. :+1:  merging.

**Pull request merged**
